"""Assert that every prediction row was generated by a model trained only on
data strictly older than the prediction date.

Definition: a prediction is leak-free iff DATE(date) >= DATE(model_cutoff).

Usage:
    python scripts/verify_no_leak.py predictions
    python scripts/verify_no_leak.py predictions_walk
"""
import sys
import sqlite3

DB = "/opt/vesign/vesign.db"


def main(table: str = "predictions"):
    c = sqlite3.connect(DB)
    cols = {r[1] for r in c.execute(f"PRAGMA table_info({table})").fetchall()}
    if "model_cutoff" not in cols:
        print(f"FAIL: {table} has no model_cutoff column — cannot verify")
        sys.exit(2)

    n_total = c.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
    n_blank = c.execute(f"SELECT COUNT(*) FROM {table} WHERE model_cutoff = ''").fetchone()[0]
    n_leak = c.execute(
        f"SELECT COUNT(*) FROM {table} WHERE model_cutoff != '' AND DATE(date) < DATE(model_cutoff)"
    ).fetchone()[0]

    print(f"{table}: {n_total:,} rows  |  blank model_cutoff: {n_blank:,}  |  leaks: {n_leak:,}")

    if n_blank > 0:
        sample = c.execute(
            f"SELECT date, ticker FROM {table} WHERE model_cutoff = '' LIMIT 5"
        ).fetchall()
        print("  sample blank rows:", sample)
    if n_leak > 0:
        sample = c.execute(
            f"SELECT date, ticker, model_cutoff FROM {table} "
            f"WHERE model_cutoff != '' AND DATE(date) < DATE(model_cutoff) LIMIT 5"
        ).fetchall()
        print("  sample leak rows:", sample)
        sys.exit(1)
    if n_blank > 0:
        sys.exit(1)
    print("OK: no leak detected")
    sys.exit(0)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "predictions")
